namespace: ecommerce
replicaCount: 1

image:
  repository: mariadb
  tag: "10.5"
  pullPolicy: IfNotPresent

service:
  type: NodePort        
  port: 3306           
  nodePort: 30306 
persistence:
  enabled: true
  size: 9Gi

credentials:
  rootPassword: "anhduy2000"
  database: "mydb"
  user: "duy"
  password: "anhduy2000"