replicaCount: 2
image:
  repository: nguyenchisang/project-backend
  tag: "v25"  # Pipeline sẽ cập nhật tag này
  pullPolicy: Always
service:
  type: ClusterIP
  port: 8080  # Thay đổi port nếu backend dùng port khác
configmap:
  mongodbUri: "mongodb://project-database-service:27017"
  redisUrl: "redis://project-redis-service:6379"
  FRONTEND_URL: "http://project-frontend-service:5173"