replicaCount: 2
image:
  repository: nguyenchisang/project-backend
  tag: "latest"  # Pipeline sẽ cập nhật tag này
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080  # Thay đổi port nếu backend dùng port khác
configmap:
  mongodbUri: "mongodb://mongo-service:27017"
  redisUrl: "redis://redis-service:6379"
  FRONTEND_URL: "http://project-frontend-service:5173"