namespace: blog
replicaCount: 1
image:
  repository: nguyenchisang/project-frontend
  tag: "v10"  # Pipeline sẽ cập nhật tag này
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
configmap:
  data:
    VITE_API_PATH: 34.101.229.235:8080
ingress:
  # className:gce
   host: ""
