namespace: blog
replicaCount: 1
image:
  repository: nguyenchisang/project-frontend
  tag: "2"  # Pipeline sẽ cập nhật tag này
  pullPolicy: Always
service:
  type: NodePort
  port: 80
configmap:
  data:
    VITE_API_PATH: "http://34.101.229.235:8080"
ingress:
  # className:gce
   host: ""
