namespace: my-namespace
replicaCount: 1
image:
  repository: madhupdevops/wanderlust-frontend-beta
  tag: "latest"  # Pipeline sẽ cập nhật tag này
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 5173
configmap:
  data:
    VITE_API_PATH: "http://project-backend-service:31100"