namespace: blog
replicaCount: 1
image:
  repository: nguyenchisang/project-frontend
  tag: "3"  # Pipeline sẽ cập nhật tag này
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
configmap:
  data:
    VITE_API_PATH: "http://project-backend-service:8080"
ingress:
  # className:gce
   host: ""
