namespace: blog
replicaCount: 1
image:
  repository: nguyenchisang/project-frontend
<<<<<<< HEAD
  tag: "v12"  # Pipeline sẽ cập nhật tag này
=======
  tag: "v13"  # Pipeline sẽ cập nhật tag này
>>>>>>> 079fa9cee2fed1a6149f3e11d5d9587bac73e2a2
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
configmap:
  data:
    VITE_API_PATH: "http://project-backend-service:8080"
ingress:
  # className:gce
   host: ""
