namespace: blog
replicaCount: 1
image:
  repository: nguyenchisang/project-frontend
  tag: "v5"  # Pipeline sẽ cập nhật tag này
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
configmap:
  data:
    API_URL: "http://34.13.77.37/api"
ingress:
  # className:gce
   host: ""
