replicaCount: 2
image:
  repository: mongo
  tag: "6.0"  # Phiên bản MongoDB
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 27017
# configmap:
#   data:
#     MONGO_INITDB_DATABASE: "blog_db"
# secret:
#   data:
#     MONGO_INITDB_ROOT_USERNAME: "YWRtaW4="  # base64: "admin"
#     MONGO_INITDB_ROOT_PASSWORD: "cGFzc3dvcmQ="  # base64: "password"
persistence:
  enabled: true
  storageClass: "standard"  # StorageClass mặc định của GKE
  accessMode: ReadWriteOnce
  size: 10Gi