apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mariadb-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  password: {{ .Values.mariadb.password | default "defaultpassword" | b64enc | quote }}