apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mariadb-secret
type: Opaque
data:
  rootPassword: {{ .Values.credentials.rootPassword | b64enc }}
  password: {{ .Values.credentials.password | b64enc }}