replicaCount: 1
namespace: blog
image:
  repository: redis
  tag: "7.0"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 6379
# secret:
#   data:
#     REDIS_PASSWORD: "cmVkaXNwYXNz"  # base64: "redispass"
resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

